// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1024.Server.Data;

#nullable disable

namespace Project1024.Server.Migrations
{
    [DbContext(typeof(VideoContext))]
    [Migration("20231107142545_Delete_Plays")]
    partial class Delete_Plays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project1024.Server.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("content");

                    b.Property<int>("CreatedTime")
                        .HasColumnType("int")
                        .HasColumnName("created_time");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int")
                        .HasColumnName("like_count");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("Project1024.Server.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LikeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("like_date");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("target_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_like");

                    b.ToTable("like", (string)null);
                });

            modelBuilder.Entity("Project1024.Server.Models.UserFollower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("FollowedId")
                        .HasColumnType("int")
                        .HasColumnName("followed_id");

                    b.Property<DateTimeOffset>("FollowedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("followed_time");

                    b.Property<int>("FollowerId")
                        .HasColumnType("int")
                        .HasColumnName("follower_id");

                    b.Property<sbyte>("IsDeleted")
                        .HasColumnType("tinyint(4)")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_user_follower");

                    b.ToTable("user_follower", (string)null);
                });

            modelBuilder.Entity("Project1024.Server.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)")
                        .HasColumnName("cover_url");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)")
                        .HasColumnName("duration");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UploadTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("upload_time");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("varchar(511)")
                        .HasColumnName("url");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Views")
                        .HasColumnType("int")
                        .HasColumnName("views");

                    b.HasKey("Id")
                        .HasName("pk_video");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_video_category_id");

                    b.ToTable("video", (string)null);
                });

            modelBuilder.Entity("Project1024.Server.Models.VideoCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_video_category");

                    b.ToTable("video_category", (string)null);
                });

            modelBuilder.Entity("Project1024.Server.Models.Video", b =>
                {
                    b.HasOne("Project1024.Server.Models.VideoCategory", "Category")
                        .WithMany("Videos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_video_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project1024.Server.Models.VideoCategory", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
